# Generated by Django 5.0.7 on 2025-09-22 17:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('primary_email', models.EmailField(max_length=255)),
                ('alternative_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('portfolio_url', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('linkedin_url', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('github_url', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('leetcode_url', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('education_degree', models.CharField(max_length=100)),
                ('education_field', models.CharField(max_length=255)),
                ('university_name', models.CharField(max_length=255)),
                ('graduation_year', models.IntegerField()),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('programming_languages', models.TextField(help_text='Comma-separated list')),
                ('python_frameworks', models.TextField(blank=True, help_text='Comma-separated list', null=True)),
                ('frontend_technologies', models.TextField(blank=True, help_text='Comma-separated list', null=True)),
                ('mobile_development', models.TextField(blank=True, help_text='Comma-separated list', null=True)),
                ('databases', models.TextField(blank=True, help_text='Comma-separated list', null=True)),
                ('cloud_devops', models.TextField(blank=True, help_text='Comma-separated list', null=True)),
                ('deployment_platforms', models.TextField(blank=True, help_text='Comma-separated list', null=True)),
                ('integrations', models.TextField(blank=True, help_text='Comma-separated list', null=True)),
                ('development_practices', models.TextField(blank=True, help_text='Comma-separated list', null=True)),
                ('professional_experience', models.TextField(help_text='JSON format or structured text')),
                ('projects', models.TextField(help_text='JSON format or structured text')),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='emailrequest',
            name='job_description',
            field=models.TextField(blank=True, help_text='Optional job description', null=True),
        ),
        migrations.AddField(
            model_name='emailsent',
            name='email_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_emails', to='mailer.emailrequest'),
        ),
        migrations.AddField(
            model_name='emailsent',
            name='resume_attached',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emailrequest',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='emailrequest',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailrequest',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_requests', to='mailer.userprofile'),
        ),
    ]
