# Generated by Django 5.0.7 on 2025-09-24 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_location', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('alternate_email', models.EmailField(blank=True, max_length=254)),
                ('alternate_phone', models.CharField(blank=True, max_length=32)),
                ('address', models.TextField(blank=True)),
                ('email_app_user', models.EmailField(blank=True, help_text='Email ID associated with app password', max_length=254)),
                ('email_app_password', models.CharField(blank=True, help_text='App password for outbound email', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='basic_info', to='accounts.userprofile')),
            ],
        ),
    ]
